image: jelaniwoods/appdev2022-base-rails

tasks:
  - before: |
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9500-9999
    onOpen: ignore

tasks:
  - before: rvm install "3.1.3" && rvm use 3.1.3 --default
    init: bundle install
    command: rails server -b 0.0.0.0

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
